services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./log:/app/log
      - ./db:/app/db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    # command: npm run dev       # ⬅️ 重点：覆盖 Dockerfile 中默认启动方式
    # working_dir: /app/frontend # ⬅️ 指定工作目录（非常重要）
    # volumes:
    #   - ./frontend:/app/frontend
    ports:
      - "5173:80"            # Vite 默认开发端口（Vue3 项目用），按需修改
    restart: unless-stopped