services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      network: host  # ⬅️ 使用主机网络模式，避免跨域问题
    image: backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
      - ./log:/app/log
      - ./backend/db:/app/backend/db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      network: host  # ⬅️ 使用主机网络模式，避免跨域问题
    # command: npm run dev       # ⬅️ 重点：覆盖 Dockerfile 中默认启动方式
    # working_dir: /app/frontend # ⬅️ 指定工作目录（非常重要）
    # volumes:
    #   - ./frontend:/app/frontend
    image: frontend:latest
    ports:
      - "5173:80"            # Vite 默认开发端口（Vue3 项目用），按需修改
    restart: unless-stopped